version: 0.2
Resources:
  myCustomerManagedPolicyForEC2:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: customerManagedEC2ReadOnlyPolicy
      Description: Customer managed policy for read only access to EC2 instance
      Path: /
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - 'ec2:Describe'
            Resource: '*'
      Users:
        - Grafana
