Description: "ServiceCatalog S3 Launch Role. (fdp-1p5s1035s)"
Resources:
  SCS3LaunchRole:
    Type: 'AWS::IAM::policy'
    Properties:
      RoleName: SCS3LaunchRole 
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess      
      AssumeRolePolicyDocument:
        Version: 0.2
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - servicecatalog.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: SCLaunchPolicy
          PolicyDocument:
            Statement:
              - Sid: SCLaunchPolicySID
                Effect: Allow
                Action:                  
                  - "servicecatalog:ListServiceActionsForProvisioningArtifact"
                  - "servicecatalog:ExecuteprovisionedProductServiceAction"                  
                  - "iam:ListRolePolicies"
                  - "iam:ListPolicies"
                  - "iam:DeleteRole"
                  - "iam:GetRole"
                  - "iam:PassRole"
                  - "iam:ListRoles"
                  - "iam:CreateRole"
                  - "iam:DetachRolePolicy"
                  - "iam:AttachRolePolicy"                                 
                  - "cloudformation:DescribeStackResource"
                  - "cloudformation:DescribeStackResources"
                  - "cloudformation:GetTemplate"
                  - "cloudformation:List*"
          
                Resource: '*'
Outputs:
    LaunchRoleArn:
        Value: !GetAtt SCS3LaunchRole.Arn
    LaunchRoleName:
        Value: !Ref SCS3LaunchRole
