version: 0.2

Resources:
  SCS3LaunchRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: SCS3LaunchRole 
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess      
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - servicecatalog.amazonaws.com
            Action:
              - 'sts:AssumeRole'
