---
version: 0.2
build: SSEAndSSLPolicy
Statement:
- Sid: DenyUnEncryptedObjectUploads
  Effect: Deny
  Principal: "*"
  Action: s3:PutObject
  Resource: arn:aws:s3:::codepipeline-ap-southeast-1-449978242056/*
  Condition:
    StringNotEquals:
      s3:x-amz-server-side-encryption: aws:kms
- Sid: DenyInsecureConnections
  Effect: Deny
  Principal: "*"
  Action: s3:*
  Resource: arn:aws:s3:::codepipeline-ap-southeast-1-449978242056/*
  Condition:
    Bool:
      aws:SecureTransport: false
