---
Resources:
    MyEC2Instance: 
      Type: AWS::EC2::Instance
      Properties: 
       AvailabilityZone: ap-northeast-1a
       ImageId: ami-0beaa649c482330f7
       InstanceType: t2.micro
       KeyName: boto3
