---
Resources:
    MyEC2Instance: 
      Type: AWS::EC2::Instance
      Properties: 
       AvailabilityZone: us-east-1b
       ImageId: ami-0b0dcb5067f052a63
       InstanceType: t2.micro
       KeyName: ashok1
