---
Resources:
    MyEC2Instance: 
      Type: AWS::EC2::Instance
      Properties: 
       AvailabilityZone: us-east-2
       ImageId: ami-0beaa649c482330f7
       InstanceType: t2.micro
       KeyName: Grafana-Ashok
