---
Resources:
    MyEC2Instance: 
      Type: AWS::EC2::Instance
      Properties: 
       AvailabilityZone: us-east-1
       ImageId: ami-026b57f3c383c2eec
       InstanceType: t2.micro
       KeyName: ashok1
