---
Mappings:
  RegionMap:
    us-east-1:
      ImageId: ami-0b0dcb5067f052a63
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.3.0.0/16
      Tags:
        - Key: Name
          Value: Devops
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: VPC
      AvailabilityZone:
        - 0
        - ""
      CidrBlock: 10.5.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: DevOps
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP from 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0
      VpcId: VPC
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        - RegionMap
        - AWS::Region
        - AMI
      InstanceType: t2.micro
      SubnetId: PublicSubnet
      KeyName: ashok1
      SecurityGroupIds:
        - WebServerSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y # update existing packages
          yum install -y httpd # install apache web server
          systemctl start httpd
          systemctl enable httpd
          echo "Hello World" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value: DevOps
